/*
 * This file is run automatically by spring-jdbc to setup the database schema
 */
SET DATABASE SQL SYNTAX PGS TRUE;
CREATE SCHEMA ANZ;

CREATE TABLE ANZ.USER_DETAILS ( 
    USER_ID BIGINT NOT NULL,
    CONSTRAINT USER_DETAILS_PKEY PRIMARY KEY (USER_ID),
    );

CREATE TABLE ANZ.ACCOUNT (
	ACCOUNT_NUMBER BIGINT NOT NULL,
	ACCOUNT_NAME VARCHAR(80) NOT NULL,
	ACCOUNT_TYPE VARCHAR(25) NOT NULL,
	BALANCE_DATE DATE NOT NULL,
	CURRENCY_CODE VARCHAR(20) NOT NULL,
	OPENING_AVAILABLE_BALANCE DECIMAL(20,2) NOT NULL,
	USER_ID BIGINT NOT NULL,
	CONSTRAINT ACCOUNT_NUMBER_PKEY PRIMARY KEY (ACCOUNT_NUMBER),
	CONSTRAINT ACCOUNT_USERDETAILS_CONSTRAINT FOREIGN KEY (USER_ID)
      REFERENCES USER_DETAILS (USER_ID) MATCH SIMPLE
      ON UPDATE NO ACTION ON DELETE NO ACTION
	);

CREATE TABLE ANZ.TRANSACTION (
	TRANSACTION_ID BIGINT NOT NULL,
    VALUE_DATE DATE NOT NULL,
    CURRENCY_CODE VARCHAR(20) NOT NULL,
    DEBIT_AMOUNT DECIMAL(20,2),
    CREDIT_AMOUNT DECIMAL(20,2),
    TRANSACTION_TYPE VARCHAR(20) NOT NULL,
    TRANSACTION_NARRATIVE VARCHAR(100),
    CONSTRAINT TRANSACTION_PKEY PRIMARY KEY (TRANSACTION_ID)
	);
	
CREATE TABLE ANZ.ACCOUNT_TRANSACTION (
	ACCOUNT_NUMBER BIGINT NOT NULL,
	TRANSACTION_ID BIGINT NOT NULL,
	PRIMARY KEY (ACCOUNT_NUMBER,TRANSACTION_ID),
  	CONSTRAINT FK_ACCOUNT_NUMBER FOREIGN KEY (ACCOUNT_NUMBER) 
             REFERENCES ACCOUNT (ACCOUNT_NUMBER),
  	CONSTRAINT FK_TRANSACTION_ID FOREIGN KEY (TRANSACTION_ID) 
             REFERENCES TRANSACTION (TRANSACTION_ID)
	);